# Generated by Django 4.1.3 on 2022-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('file', models.FileField(default='', upload_to='file/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=80)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
