# Generated by Django 4.1.3 on 2022-12-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userNotifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('levelOfPriority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Resolved')], max_length=6)),
            ],
        ),
    ]
