# Generated by Django 4.1.3 on 2022-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userNotifications', '0002_createnewmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewmessage',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createnewmessage',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Resolved')], default='open', max_length=6),
        ),
    ]
